version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  warranty:
    image: warranty:latest
    container_name: warranty
    command: ["wait-for-it", "postgres:5432", "-s", "-t", "0", "--", "/opt/warranty/entrypoint.sh"]
    build:
      context: service_warranty
    environment:
      PORT: 8180
    ports:
      - 8180:8180

  warehouse:
    image: warehouse:latest
    container_name: warehouse
    command: ["wait-for-it", "postgres:5432", "-s", "-t", "0", "--", "/opt/warehouse/entrypoint.sh"]
    build:
      context: service_warehouse
    environment:
      WARRANTY_URL: warranty:8180
      PORT: 8280
    ports:
      - 8280:8280

  order:
    image: order:latest
    container_name: order
    command: ["wait-for-it", "postgres:5432", "-s", "-t", "0", "--", "/opt/order/entrypoint.sh"]
    build:
      context: service_order
    environment:
      WAREHOUSE_URL: warehouse:8280
      WARRANTY_URL: warranty:8180
      PORT: 8380
    ports:
      - 8380:8380

  store:
    image: store:latest
    container_name: store
    command: ["wait-for-it", "postgres:5432", "-s", "-t", "0", "--", "/opt/store/entrypoint.sh"]
    build:
      context: service_store
    environment:
      ORDER_URL: order:8380
      PORT: 8480
    ports:
      - 8480:8480

volumes:
  db-data: