version: "3"
services:

  warranty:
    image: warranty:latest
    container_name: warranty
    command: ["wait-for-it", "postgres:5432", "-s", "-t", "0", "--", "/opt/warranty/entrypoint.sh"]
    build:
      context: service_warranty


  warehouse:
    image: warehouse:latest
    container_name: warehouse
    command: ["wait-for-it", "postgres:5432", "-s", "-t", "0", "--", "/opt/warehouse/entrypoint.sh"]
    build:
      context: service_warehouse

  order:
    image: order:latest
    container_name: order
    command: ["wait-for-it", "postgres:5432", "-s", "-t", "0", "--", "/opt/order/entrypoint.sh"]
    build:
      context: service_order


  store:
    image: store:latest
    container_name: store
    command: ["wait-for-it", "postgres:5432", "-s", "-t", "0", "--", "/opt/store/entrypoint.sh"]
    build:
      context: service_store

volumes:
  db-data: